In [5]:
import numpy

vector = numpy.array([1,3,8,2]);#向量
print(vector)
matrix = numpy.array([[1,2],[6,5],[8,9]])#矩阵
print(matrix);

[1 3 8 2]
[[1 2]
 [6 5]
 [8 9]]


In [4]:
print(vector.shape);
print(matrix.shape);

(4,)
(3, 2)


In [5]:
nums = numpy.array([1,3,8,10]);
print(nums);
print(nums.dtype);


[ 1  3  8 10]
int32


In [10]:
nums2 = numpy.array([1,3,8.5,10]);
print(nums2);
print(nums2.dtype);

[ 1.   3.   8.5 10. ]
float64


In [17]:
nums3 = numpy.array([1,12,8.5,'10']);
print(nums3);
print(nums3.dtype);

['1' '12' '8.5' '10']
<U32


In [21]:
#numpy取txt文件数据，后面用pandas，这里不常用，只试一例看看
users = numpy.genfromtxt("user.txt",delimiter = ",", dtype=str, skip_header=1);
#参数：文件路径，数据分割符，类型，是否要第一行。
print(users);

[['1989' '天天' '女' 'IT']
 ['1860' '大地' '男' '巫师']
 ['1990' '旺旺旺' '女' '网红']
 ['1870' '毛毛毛' '男' '汽修']]


In [24]:
print(users[0,3]);#取第0个样本第3号值，索引从0开始


IT


In [25]:
print(users[1,0:3]);#取第1个样本第0到2号值，包前不包后

['1860' '大地' '男']


In [26]:
print(users[:,1]);#取:所有样本第1号值

['天天' '大地' '旺旺旺' '毛毛毛']


In [30]:
print(users[2:4,1:4])#取第2到3号样本第1到3个值

[['旺旺旺' '女' '网红']
 ['毛毛毛' '男' '汽修']]


In [51]:
vector2 = numpy.array([1,3,50,10,8]);
print(vector2 == 10)#注意这行和下面一行返回的不同。
vector2 == 10#返回的是里面元素每一个比对的布尔值


[False False False  True False]


array([False, False, False,  True, False])

In [40]:
matrix2 =numpy.array([['1989', '天天', '女', 'IT'],
 ['1860', '大地', '男' ,'巫师'],
 ['1990', '旺旺旺', '女', '网红'],
 ['1870', '毛毛毛', '男', '汽修']]);
print(matrix2)
print(matrix2 == '女');#注意这个和下面一条打印出的值有什么不同。
matrix2 == '女'#挨个比对，反bool的矩阵。

[['1989' '天天' '女' 'IT']
 ['1860' '大地' '男' '巫师']
 ['1990' '旺旺旺' '女' '网红']
 ['1870' '毛毛毛' '男' '汽修']]
[[False False  True False]
 [False False False False]
 [False False  True False]
 [False False False False]]


array([[False, False,  True, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [53]:
vector3 = numpy.array([1,10,5,60,14]);
trueIndex = (vector3 == 10);#这个值可以做索引，再次传进数组中取出为true的值，过滤掉false值。
print(trueIndex);
print(vector3[trueIndex]);

[False  True False False False]
[10]


In [57]:
matrix3 =numpy.array([['1989', '天天', '女', 'IT'],
 ['1860', '大地', '男' ,'巫师'],
 ['1990', '旺旺旺', '女', '网红'],
 ['1870', '毛毛毛', '男', '汽修']]);
trueIndex = (matrix3[:,1] =='旺旺旺')
#矩阵的定位到具体的行列。所有样本中第1号列为旺旺旺的
print(trueIndex)
print(matrix3[trueIndex,:])
#取出这个样本。


[False False  True False]
[['1990' '旺旺旺' '女' '网红']]


In [66]:
vector4 = numpy.array([1,20,10,36,84,5])#numpy.array的作用是生成矩阵对象，不加就是一个列表。
if1 = (vector4 == 20) & (vector4 == 5)#与，一个&，两条件加括号
if2 = (vector4 == 20 ) | (vector4 == 5)#或,一个|，两条件加括号
print(if1)
print(if2);

[False False False False False False]
[False  True False False False  True]


In [67]:
vc5 = numpy.array([1,20,6,50,45,6])
if1 = (vc5 == 1)|(vc5 ==6)
vc5[if1]=100;#给满足条件的做替换
print(vc5)

[100  20 100  50  45 100]


In [70]:
mt5 =numpy.array([['1989', '天天', '女', 'IT'],
 ['1860', '大地', '男' ,'巫师'],
 ['1990', '旺旺旺', '女', '网红'],
 ['1870', '毛毛毛', '男', '汽修']]);
trueIndex = (matrix3[:,1] =='旺旺旺')
#把上面“旺旺旺”和“毛毛毛”替换成“小狗子”
if1 = (mt5[:,1]=='旺旺旺')|(mt5[:,1]=='毛毛毛')
mt5[if1,1] = '小狗子';
print(mt5)

[['1989' '天天' '女' 'IT']
 ['1860' '大地' '男' '巫师']
 ['1990' '小狗子' '女' '网红']
 ['1870' '小狗子' '男' '汽修']]


In [71]:
#类型转换 astype,dtype是返回它的类型
vc6 = numpy.array(['1','2','18'])
print(vc6.dtype)
print(vc6)
vc6 = vc6.astype(float);
print(vc6.dtype)
print(vc6)

<U2
['1' '2' '18']
float64
[ 1.  2. 18.]


In [72]:
vc6.min()#返回最小值

1.0

In [79]:
mt6 = numpy.array([
    [1,1,1],
    [10,10,10],
    [100,100,100]
])
print(mt6.sum(axis=1))#按行加
print(mt6.sum(axis=0))#按列加
mt6.sum(axis=0)

[  3  30 300]
[111 111 111]


array([111, 111, 111])

In [9]:
mt7 = numpy.array([
     [1,2,3],
    [10,20,30],
    [100,200,300]
])
print(mt7.max(axis=1))#按行取最大值，返回新矩阵
print(mt7.max(axis =0))#取列里最大的，返回新矩阵

[  3  30 300]
[100 200 300]


In [8]:
import numpy as np
#以下numpy 代名 np
#头部引用import numpy as np，即可用np代替numpy，用numpy也不影响
print(np.arange(8))#生成一个0到8的一行vector向量数
a = np.arange(8).reshape(2,4)#重组成2行4列的矩阵matrix
a


[0 1 2 3 4 5 6 7]


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [95]:
a.shape#可用于debug，每部行都打出来，找BUG问题

(2, 4)

In [109]:
a.ndim#当前矩阵的纬度，只有行列，二维

2

In [113]:
#a.dtype#返回dtype('int32')
a.dtype.name#返回int32

'int32'

In [116]:
a.size#a的元素总个数

8

In [104]:
b = np.arange(8).reshape(8)#重组成只有一行的一维的向量
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [114]:
b.ndim#一维

1

In [6]:


#==矩阵初始化==
np.zeros((2,3))#生成2行3列的元素都为浮点0的matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,2),dtype = np.int32)#初始化为都是1的，不用默认浮点数，用int

array([[1, 1],
       [1, 1]])

In [47]:
from numpy import pi#引pi 3.1415926
#arange初始化一组数
print(np.arange(1,10,2))#参娄：起，终，步长，+2
np.arange(1,2*pi,0.1)#起终值可以是计算的

[1 3 5 7 9]


array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2])

In [14]:
np.arange(0,2,0.2)#arange初始化一组浮点数

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [16]:
np.arange(6).reshape(2,3)#arange初始化0到6之前的整数，重组成2行3列

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
np.random.random((3,3))#random模块下random函数，随机生成0到1之间的数，排成3行3列

array([[0.0102628 , 0.30424206, 0.77995589],
       [0.00412132, 0.6846139 , 0.38219892],
       [0.02161787, 0.60524916, 0.64838402]])

In [62]:
mt8= np.random.random((5,2))*10 #生成0-10之间5行2列随机浮点数
print(mt8)
print(mt8.astype(int).reshape(2,5))#转成0到10之音随机整数2行5列

(np.linspace(0,10,10)).astype(int).reshape(2,5)#效果同上，


[[3.93403888 9.15478952]
 [7.59067502 6.34063507]
 [5.28118416 1.80213103]
 [0.05527028 7.45437411]
 [7.01297331 9.52627831]]
[[3 9 7 6 5]
 [1 0 7 7 9]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 10]])

In [56]:
#.linspace(起值到终值之间，生成多少个随机数)并可计算 VS arange类似，生成起，始，步长变化，起终值可以计算。
print(np.linspace(0, 10*pi,10))#起值，终值，生成多少个随机数
np.linspace(1,10,10)#生成1到10之间的随机数10个

[ 0.          3.4906585   6.98131701 10.47197551 13.96263402 17.45329252
 20.94395102 24.43460953 27.92526803 31.41592654]


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [96]:
#其它数学运算公式也支持
print(np.sin(60))
print(np.cos(90))
print(np.tan(90))
print(np.arctan(90))

-0.3048106211022167
-0.4480736161291701
-1.995200412208242
1.5596856728972892


In [110]:
#===相量vector，一维矩阵运算===
#先造两个一维矩阵，打印出来
a = np.array([10,20,30])
b = np.arange(1,4)
print(a)
print(b)
#开始矩阵运算
c = a*b#【会是两个一维矩阵一一对应计算。注：个数结构必须相同】
print(c)
c = c -1#每位-1
print(c)
b = b**3#每位的3次幂，3个自己相乘
print(b)
print(a<20)#判断反回布尔值

[10 20 30]
[1 2 3]
[10 40 90]
[ 9 39 89]
[ 1  8 27]
[ True False False]


In [128]:
#矩阵运算 matrix
#先造两个矩阵，打印出来
mtA = np.array([
    [2,3],
    [20,30]
])
mtB = np.array([
    [1,10],
    [100,1000]
])
print(mtA)
print(mtB)
print("----求内积mtA*mtB----")
print(mtA*mtB)#个个位置分别对应相乘
print("----mtA+mtB----")
print(mtA+mtB)#第个位置对应相加


[[ 2  3]
 [20 30]]
[[   1   10]
 [ 100 1000]]
----求内积mtA*mtB----
[[    2    30]
 [ 2000 30000]]
----mtA+mtB----
[[   3   13]
 [ 120 1030]]


In [129]:
#---矩阵乘 dot：按照矩阵乘法的规则来运算
#为了例于理解找规律，重新造两组好辨认值的matrix，打印出来
mtC = np.array([
    [1,2],
    [10,20]
])
mtD = np.array([
    [100,200],
    [1000,2000]
])
print(mtC)
print(mtD)
print("---------")
print("---矩阵乘 dot：按照矩阵乘法的规则来运算 mtC.dot(mtD)或np.dot(mtC,mtD),一样的 ------")
print(mtC.dot(mtD))
#2100 = 1*100+2*1000，C一行与D一列运算，运算方式：对应位相乘，和相加，
#4200 = 1*200+2*2000，C一行与D二列运算，运算方式：同上，
#（C一行运算完了，抛开不看）
#21000 = 10*100+20*1000, C二行与D一列运算，运算方式：同上，
#42000 = 10*200+20*2000，C二行与D二列运算，运算方式：同上，
#===【总结，行列按位对乘再加（行*列+行*列，本来从上面很多例可看出numpy运算特点可总结：行*列就是对应位相乘），以一个为基准遍历下去。】===
#==【所以上面C的行列数要和D的行列数能匹配上，一个是2行3列，另一个是3行两列，即翻转90度，刚好一到致】==

[[ 1  2]
 [10 20]]
[[ 100  200]
 [1000 2000]]
---------
---矩阵乘 dot：按照矩阵乘法的规则来运算 mtC.dot(mtD)------
[[ 2100  4200]
 [21000 42000]]


In [131]:
#==感受下==
mtE = np.array([
    [1,2,3],
    [10,20,30]
])
mtF = np.array([
    [100,200],
    [1000,2000],
    [10000,20000]
])
print(np.dot(mtE,mtF))#感受下

[[ 32100  64200]
 [321000 642000]]


In [136]:
#==第三章 5 Numpy 常用函数==

#exp(x)指数函数，e的x次方，
vc1 = np.arange(10);
print(vc1)
print(np.exp(vc1))#e的0，1，2，3，4，次方（...个自己相乘）
print(np.sqrt(vc1))#开方，开0,1,2,3...9次开方（...个自己 相乘）
#关于e
#e=2.71828……是“自然律”的一种量的表达。“自然律”的形象表达是螺线。螺线的数学表达式通常有下面五种：（1）对数螺线；（2）阿基米德螺线；（3）连锁螺线；（4）双曲螺线；（5）回旋螺线。
#e=(1+1/x)^x 其中，x是无穷大
#用文字描述就是：1与无穷小的和的无穷大次方的值
#e是“自然律”的精髓，在数学上它是函数：
#1（1+——）
#X的X次方，当X趋近无穷时的极限。
#人们在研究一些实际问题，如物体的冷却、细胞的繁殖、放射性元素的衰变时，都要研究
#1（1+——）
#X的X次方，当X趋近无穷时的极限。正是这种从无限变化中获得的有限，从两个相反方向发展（当X趋向正无穷大的时，上式的极限等于e=2.71828……，当X趋向负无穷大时候，上式的结果也等于e=2.71828……）得来的共同形式，充分体现了宇宙的形成、发展及衰亡的最本质的东西。
#【记起来一些，e的x次幂，x负无穷大时 结果趋向于0，x正无穷时，结果趋向正无穷大】

[0 1 2 3 4 5 6 7 8 9]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [148]:
#===类型转换====
a = 10*np.random.random((3,4))#两个括号注意，
print(a)
print(np.floor(a))#取整，还是浮点型
print(np.int32(a))#取整，整形。【注意：上面有一例用了a.astype('int')，这里是np.int32(a)】

[[5.50760558 7.88553393 2.49798839 9.14033422]
 [1.17994646 9.33903041 6.83148257 4.30189261]
 [8.89782012 1.80669996 8.37382719 7.88544455]]
[[5. 7. 2. 9.]
 [1. 9. 6. 4.]
 [8. 1. 8. 7.]]
[[5 7 2 9]
 [1 9 6 4]
 [8 1 8 7]]


In [167]:
b = np.arange(12).reshape(2,6)
print(b)
print(b.ravel())#多行抻成一行

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [168]:
b.shape = (3,4)#重组行列，可以用.shape = (行，列)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [169]:
print(b.T)#转置，行列颠倒,值也跟着过去，注意


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [188]:
#===拼数据，拼特征【注意下面的变量名和上面的如果重了，会改变上面的，】===
a_1 = np.int32(10*np.random.random(6).reshape(2,3));
b_1 = np.int32(10*np.random.random(12).reshape(4,3));
print("==a,b print==")
print(a_1)
print(b_1)
print("===np.vstack 竖着拼接，列数要一致===")
print(np.vstack((a_1,b_1)))#np.vstack((行，列))拼接，竖着拼两个列数要一致，
print("==c,d print==")
c_1 = np.int32(10*np.random.random(12).reshape(2,6));
d_1 = np.int32(10*np.random.random(6).reshape(2,3));
print(c_1)
print(d_1)
print("===np.hstack 横着拼接，行数要一致===")
print(np.hstack((c_1,d_1)))#np.hstack((行，列))横着拼，注意，行数要一致。


==a,b print==
[[8 4 7]
 [7 7 4]]
[[5 8 2]
 [4 3 8]
 [5 6 5]
 [4 1 3]]
===np.vstack 竖着拼接，列数要一致===
[[8 4 7]
 [7 7 4]
 [5 8 2]
 [4 3 8]
 [5 6 5]
 [4 1 3]]
==c,d print==
[[4 8 6 1 9 4]
 [1 6 2 5 5 7]]
[[1 5 5]
 [9 1 6]]
===np.hstack 横着拼接，行数要一致===
[[4 8 6 1 9 4 1 5 5]
 [1 6 2 5 5 7 9 1 6]]


In [209]:
#====切割===
#mt_sp = np.floor(10*np.random.random((2,12)))#注意，是floor，不是float
mt_sp = np.arange(24).reshape(2,12)#为方便看，用规律变化的
print(mt_sp)
print("===把上面矩阵横向等分成三份===")
print(np.hsplit(mt_sp,3))#hsplit 横向分，horizontal,vsplit 纵向分开 vertical
print("===把上面矩阵横向以某点为界分三份==")
print(np.hsplit(mt_sp,(3,5)))#以索引3-5为界分三份，不包括5号
mt_sp2 = np.copy(mt_sp).T;#【复制mt_sp给mt_sp2，再转置。】
print(mt_sp2)
print("===把上面矩阵纵向等分成三份===")
print(np.vsplit(mt_sp2,3))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
===把上面矩阵横向等分成三份===
[array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])]
===把上面矩阵横向以某点为界分三份==
[array([[ 0,  1,  2],
       [12, 13, 14]]), array([[ 3,  4],
       [15, 16]]), array([[ 5,  6,  7,  8,  9, 10, 11],
       [17, 18, 19, 20, 21, 22, 23]])]
[[ 0 12]
 [ 1 13]
 [ 2 14]
 [ 3 15]
 [ 4 16]
 [ 5 17]
 [ 6 18]
 [ 7 19]
 [ 8 20]
 [ 9 21]
 [10 22]
 [11 23]]
===把上面矩阵纵向等分成三份===
[array([[ 0, 12],
       [ 1, 13],
       [ 2, 14],
       [ 3, 15]]), array([[ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19]]), array([[ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23]])]


In [216]:
#===复制【python里面变量相等，改后面变量时，前面变量也会变，要想改新的，旧的不变，需要复制，切记】===
vc_cp = np.arange(6)
print(vc_cp)
vc_cp2 = vc_cp
print(vc_cp)
vc_cp2.shape = 2,3#重组成2行3列
print(vc_cp2)
print(vc_cp)#上面改了2，1也被改了
print(vc_cp.shape)
print(id(vc_cp))
print(id(vc_cp2))#第个变量都有一个id，1和2完全相等了。好比一个快捷方式的链接引用，改一个另一个也跟着改了。

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
(2, 3)
818148759872
818148759872


In [223]:
#===浅层复制view===
vc_cp3 = vc_cp.view()
print(vc_cp3 is vc_cp)
vc_cp3.shape = 1,6
print(vc_cp3)
print(vc_cp)#上面改了行列结构，原矩阵没受影响
vc_cp3[0,1] = 10
print(vc_cp3)
print(vc_cp)#【但上面改了一个值，原矩阵也一起变了，所以view只可以保障视图结构不变，值还是会牵连变，所以不建议用】
print(id(vc_cp))
print(id(vc_cp3))#id也是不一样了

False
[[ 0 10  2  3  4  5]]
[[ 0 10  2]
 [ 3  4  5]]
[[ 0 10  2  3  4  5]]
[[ 0 10  2]
 [ 3  4  5]]
818148759872
818148935600


In [227]:
#==要想完全复制一个全新的，不连带改的，可以用深度复制copy==
vc_cp4 = vc_cp.copy()
print(vc_cp)
print(vc_cp4)
vc_cp4.shape = 1,6
print("=======")
print(vc_cp4)
print(vc_cp)#新行列结构没影响到旧的
vc_cp4[0,2]=20
print("======")
print(vc_cp4)
print(vc_cp)#新值没影响到旧值
print(id(vc_cp4))
print(id(vc_cp))#id不同

[[ 0 10  2]
 [ 3  4  5]]
[[ 0 10  2]
 [ 3  4  5]]
[[ 0 10  2  3  4  5]]
[[ 0 10  2]
 [ 3  4  5]]
[[ 0 10 20  3  4  5]]
[[ 0 10  2]
 [ 3  4  5]]
818148936480
818148759872


In [245]:
#=====找最大值的索引号===
#mt_mx = np.sin(np.arange(12)).reshape(3,4)
#mt_mx = np.linspace(1,12,12).reshape(3,4)#1到12，生成12个随机数,注意这个还是按顺序，不是随机的。
mt_mx = np.floor(10*np.random.random(12).reshape(3,4))
print(mt_mx)
ind = mt_mx.argmax(axis = 0);
print(ind)#返回最大值的索引号，组成新矩阵。 axis = 0列中，1行中
#把上面索引位的值取出来
print(mt_mx[ind,range(mt_mx.shape[1])])#【ind值的矩阵个数为老矩阵的列数.shape返回(行，列)，.shape[1]取出列数】
#【argmax最大数索引所在值取出。】

[[6. 9. 0. 9.]
 [1. 7. 3. 6.]
 [8. 0. 1. 7.]]
[2 0 1 0]
[8. 9. 3. 9.]


In [253]:
#==复制 tile瓦片==
vc_tl = np.array([1,20,6,8])
print(vc_tl)
print(np.tile(vc_tl,(5,2)))#tile复制一样的，复制成几行几列

[ 1 20  6  8]
[[ 1 20  6  8  1 20  6  8]
 [ 1 20  6  8  1 20  6  8]
 [ 1 20  6  8  1 20  6  8]
 [ 1 20  6  8  1 20  6  8]
 [ 1 20  6  8  1 20  6  8]]


In [261]:
#==排序==
vc_st = np.array([1,20,6,8,10,6]).reshape(2,3)
print("===sort===")
print(vc_st)
vc_st_n = np.sort(vc_st,axis=1)#按行排序，每一行单独排，打乱
print(vc_st_n)
vc_st2 = np.array([1,15,61,8,10,6]).reshape(2,3)
print("====argsort====")
print(vc_st2);
vc_st_n2 = np.argsort(vc_st2,axis=0)#排序后生成索引矩阵。axis=0按列排序
print(vc_st_n2);

===sort===
[[ 1 20  6]
 [ 8 10  6]]
[[ 1  6 20]
 [ 6  8 10]]
====argsort====
[[ 1 15 61]
 [ 8 10  6]]
[[0 1 1]
 [1 0 0]]
