In [1]:
#Task7
#pandas分类使用，提高性能和内存使用率
#统计和机器学习中使用的分类数据的工具

In [2]:
#unique\value_counts 从数组提取不同值，并分别计算频率
import pandas as pd
import numpy as np

In [3]:
values = pd.Series(['apple','orange','apple','apple']*2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [4]:
values.unique()#取不重复值

array(['apple', 'orange'], dtype=object)

In [7]:
values.value_counts()#【词频统计】

apple     6
orange    2
dtype: int64

In [8]:
#维表向量化(Dimension Table)
values2 = pd.Series([0,1,0,0]*2)
print(values2)

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64


In [9]:
dim = pd.Series(['apple','orange'])
print(dim)

0     apple
1    orange
dtype: object


In [10]:
#dim字符串值.take(values2向量表示值)
dim.take(values2)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [11]:
values3 = pd.Series([0,1]*3)
dim.take(values3)

0     apple
1    orange
0     apple
1    orange
0     apple
1    orange
dtype: object

In [12]:
values4 = pd.Series([0,1])
dim.take(values4)

0     apple
1    orange
dtype: object

In [ ]:
#【上面这种用整数表示一组值的方法称为分类或字典编码表示法。
#太强大了！！文本向量化的雏形 2019/7/13】
#【分类表示可以在分析数据时大大提高性能。通过操作编码来控制数据】


In [13]:
#分类类型category
#先造一组数据
fruits = ['apple','orange','apple','apple']*2
N = len(fruits)
df = pd.DataFrame({'fruit':fruits,
                  'basket_id':np.arange(N),
                  'count':np.random.randint(3,15,size=N),#随机数可以指定起止和个数用size
                  'weight':np.random.uniform(0,4,size=N)},#随机采样浮点数
                   columns = ['basket_id','fruit','count','weight'])
df

basket_id   fruit  count    weight
0          0   apple      7  2.063178
1          1  orange     11  0.697573
2          2   apple     12  2.512381
3          3   apple     14  2.341174
4          4   apple     10  0.675012
5          5  orange      9  0.418491
6          6   apple     14  0.757354
7          7   apple      6  3.725533

In [14]:
df['fruit']#拿出一列看下，是object对象类型

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: object

In [17]:
#把上面一列转成分类类型 通过.astype('category')
fruit_cat = df['fruit'].astype('category')
fruit_cat
#看结果，成功转成了分类对象，里面只有两个值apple,orange
#【它是一个pandas.Categorical的实例】

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [18]:
c = fruit_cat.values
type(c)

pandas.core.arrays.categorical.Categorical

In [19]:
#分类对象除了上面的categories （看值和类型）还有codes（看代表分类编码）属性
c.categories


Index(['apple', 'orange'], dtype='object')

In [20]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [24]:
#==数组变分类的方法：==
#1、 上面取一列【.astype('category')】转分类介绍完了，
#此法不认定指定的分类顺序，输入什么样就什么顺序
#2、 下面看也可以用【pd.Categorical】 Python序列直接创建
#
#3、 还可以用【from_codes】构造器（前提是已经从其它源获得了分类编码）
#可以指定一个有意义的顺序
my_categories = pd.Categorical(['foo','bar','baz','foo','bar'])
print(my_categories)
print(my_categories.codes)

[foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]
[2 0 1 2 0]


In [27]:
codes = [1,0,2,1,0]#编号数字要连续？2换成3不行
my_cats2 = pd.Categorical.from_codes(codes,['foo','bar','baz'])
print(my_cats2)
print(my_cats2.codes)

[bar, foo, baz, bar, foo]
Categories (3, object): [foo, bar, baz]
[1 0 2 1 0]


In [28]:
my_cats3 = pd.Categorical.from_codes(codes,['foo','bar','baz'],ordered=True)
print(my_cats3)
print(my_cats3.codes)

[bar, foo, baz, bar, foo]
Categories (3, object): [foo < bar < baz]
[1 0 2 1 0]


In [34]:
#【.as_ordered 无序的可以通过这个排序？】
my_catsNew = pd.Categorical(['bar','foo','baz']).as_ordered()
print(my_catsNew)
print(my_catsNew.codes)

[bar, foo, baz]
Categories (3, object): [bar < baz < foo]
[0 2 1]


In [ ]:
#用分类做计算，提高效率===》》》===图7087