# 数据分析 numpy 100题


In [1]:
import numpy as np

In [5]:
print(np.__version__)#打印版本号
#print(np.show_config())#打印numpy配置信息

1.16.2


In [7]:
#创建一个长度为10的空向量(都为0)
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
#查看数组内存大小
print(z.size)#10 数据元素个数
print(z.itemsize)#8 8字节 ndarray 对象中每个元素的大小，以字节为单位

10
8


In [11]:
#查看numpy中add函数的说明文档
#print(np.info(np.add))
#add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

In [12]:
#创建一个长度为10并且除了第五个值为1的空向量
z2 = np.zeros(10)
z2[4] = 1
print(z2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
#创建一个值域范围从10到49的向量
#z3 = np.arr(np.arange(10,49))#
z3 = np.arange(10,50)#直接np.arange()即可
print(z3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
#反转一个向量(第一个元素变为最后一个)
#print(np.reverse(z3))
z4 = z3[::-1]#【::-1 把数组反转倒排】
print(z4)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [17]:
#创建一个 3x3 并且值从0到8的矩阵
z5 = np.arange(0,9).reshape(3,3)#arange(9)即可，从0开始的前面0可省
print(z5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
#找到数组[1,2,0,0,4,0]中非0元素的位置索引 
z6 = [1,2,0,0,4,0]
#z6.index(z6.values !1=0)
#print(z6)
print(np.nonzero(z6))#【np.nonzero 返回非0元素索引】

(array([0, 1, 4], dtype=int64),)


In [22]:
#创建一个 3x3 的单位矩阵【对角线两边一样，叫单位矩阵】
print(np.eye(3,3))#【行列传值进去即可】

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
#创建一个 3x3x3的随机数组
print("111:",np.random.randn(3,3,3))#【np.random.randn(行，列,组)创建3组3行3列随机数据】 （3,3）为行列两维
#print("222:",np.random.random((3,3,3)))#同上

111: [[[-1.47490065  1.30910695 -0.29284134]
  [ 1.6594273   0.35197031 -1.30283066]
  [-1.35387873  0.1715873  -1.02298599]]

 [[-1.17598821 -0.80138195  0.31248565]
  [-0.64302928 -0.4081859   0.65137354]
  [-1.43974445 -2.04352281  0.21966452]]

 [[-1.28760514 -0.1797926  -1.84176098]
  [-0.15647743  0.41916723 -0.83682258]
  [-0.65099978 -0.46529617  0.42633292]]]


In [42]:
#创建一个 10x10 的随机数组并找到它的最大值和最小值
z7 = np.random.randn(10,10)
print(z7)
print("最大值：",np.max(z7))
print("最大值",z7.max())
#【以下方法也可】
print("最小值：",np.min(z7))
print("最大值",z7.min())

[[ 2.79105288e-01  7.28547647e-01 -1.48250926e-01  2.53340856e-01
  -2.91749521e-02 -1.68987392e+00 -1.99479130e-01 -1.04784884e+00
   6.11570377e-01 -1.31879487e+00]
 [ 1.99408928e+00 -3.70025363e-02 -5.81361922e-01 -5.24944792e-01
  -6.34798162e-01  7.41426949e-01  1.57913317e+00  8.34302946e-01
  -6.34511343e-02 -3.58415009e-01]
 [ 1.08987955e+00  9.18634149e-01  9.11274488e-01 -3.39876728e-01
  -5.71138177e-01  1.20326189e+00 -2.06021814e-01  1.74337771e+00
  -2.34097832e+00 -1.03170595e+00]
 [-3.33083010e-01  4.31057083e-01  1.08544876e+00 -1.58306862e+00
   3.19594269e-01  2.39694468e-01 -6.81110588e-01  3.62117447e-01
   4.25693824e-01  2.25693271e-01]
 [-1.31294105e+00  5.59262974e-01  1.29870759e-01 -1.69597377e+00
  -6.42649845e-01  2.67216358e+00 -3.82209540e-01 -9.01108355e-01
   2.42693460e-01  1.26458824e-01]
 [ 9.71073378e-01  9.16367754e-01 -7.97697874e-01  1.98117597e-01
   3.48071333e-01  3.00553155e-01 -6.04899510e-01 -1.00614109e-01
  -1.83052532e-01  8.57642469e-01

In [44]:
#创建一个长度为30的随机向量并找到它的平均值
z8 = np.random.randn(30)
print(z8)
print("平均值：",z8.mean())

[-0.43274003  1.28582234 -0.83085437 -0.46475154  0.62375605 -0.09859179
 -0.34649371 -0.40996203  0.21972309  0.19365678  0.73115465  0.62423358
 -0.13362529 -1.20789732  0.07831041 -0.04233411  0.15434415 -0.43631505
 -0.21588022  2.29847983 -0.24874772 -1.25660916 -0.64689348  0.16760581
 -1.02722347  1.87347139  0.50329465  0.10883231 -0.61774618  0.06367624]
平均值： 0.01698986009417562


In [52]:
#创建一个二维数组，其中边界值为1，其余值为0
z9 = np.ones((10,10))
print(z9)
z9[1:-1,1:-1]=0
print(z9)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [56]:
#给数组用0填充的边界
z10 = np.ones((3,3))#双重括号，注意
z10 = np.pad(z10,pad_width=1,mode='constant',constant_values=0)
print(z10)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [62]:
0 * np.nan#nan
np.nan == np.nan#False
np.inf > np.nan#False
np.nan - np.nan#nan
0.3 == 3 * 0.1#false
#nan 非数字 inf infinity无穷

False

In [73]:
#创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置
z11 = np.zeros((5,5))
print(z11)
Z11 = np.diag(1+np.arange(4),k=-1)#0到3都加1变到1到4，k=-1在对角下下
print(Z11)
Z11 = np.diag(np.ones(4)+1,k=0)#diag填充对角线,k=0对角线，-1对角线下移一位，+1对角线上移一位
print(Z11)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


In [83]:
#创建一个8x8 的矩阵，并且设置成棋盘样式
#【:: 意思 start : end : step间隔步长。行从1起到尾，间隔2个，设为1】
z12 = np.zeros((8,8))
#z12[1::2] =1 
#print(z12)
#z12[:,::2] =1 #列::2从0开始到尾，间隔2个
#print(z12)
z12[1::2,::2] = 1
#print(z12)
z12[::2,1::2]=1
print(z12)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [93]:
#用tile函数创建一个 8x8的棋盘样式矩阵
#【tile横向纵向复制矩阵】
z14 = np.tile(np.array([[0,5],[1,0]]),(3,3))
print(z14)

[[0 5 0 5 0 5]
 [1 0 1 0 1 0]
 [0 5 0 5 0 5]
 [1 0 1 0 1 0]
 [0 5 0 5 0 5]
 [1 0 1 0 1 0]]


In [89]:
#考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么
z13 = np.arange(6*7*8).reshape(6,7,8)#【6，7，8维数个数就是6*7*8】
print(z13)
print("第100个元素的下标索引位置：",np.unravel_index(100,(6,7,8)))#【unravel_index获取数据中某个值的下标】

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [99]:
#对一个5x5的随机矩阵做归一化 (x - min) / (max - min)
z15 = np.random.random((5,5))
print(z15)
z16 = (z15-z15.min())/(z15.max() - z15.min())
print(z16)

[[0.1143995  0.06283023 0.09090944 0.10121299 0.76857741]
 [0.81191337 0.73158852 0.34547789 0.92070677 0.24488332]
 [0.78921967 0.522654   0.54628115 0.10019974 0.62686799]
 [0.01747023 0.01615    0.19919705 0.91762014 0.36523724]
 [0.79255033 0.13627566 0.12814669 0.38921649 0.77134305]]
[[0.10861618 0.05160564 0.0826476  0.09403831 0.83181889]
 [0.87972739 0.79092716 0.36407652 1.         0.25286784]
 [0.85463919 0.55994717 0.58606731 0.09291815 0.67515717]
 [0.00145954 0.         0.20236104 0.99658769 0.38592077]
 [0.85832129 0.13280057 0.12381388 0.41243016 0.83487634]]


In [101]:
#创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype，自定义类型float64 = np.dtype('float64')
color = np.dtype([("r", np.ubyte, 1),
                   ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [102]:
#一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么dot 矩阵点乘
z17 = np.ones((5,3))
z18 = np.ones((3,2))
zMulti = np.dot(z17,z18)
print(zMulti)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [115]:
#给定一个一维数组，对其在3到8之间的所有元素取反
z19 = np.arange(15)
#z20 = z19[3:9].reverse()
z19[3:9] *= -1#【3到9之间*= -1,不会把变的切出来】[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14]
print(z19)
z19_2 = np.arange(15)
#z19[3:9] * -1 #【不加*= 不会赋回去替换掉原来的】[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
z20 = z19_2[3:9] * -1#【*，最后赋值给新变量，切出来了】[-3 -4 -5 -6 -7 -8]
print(z20)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14]
[-3 -4 -5 -6 -7 -8]


In [117]:
#【=========np.sum ？=======================】
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [124]:
#考虑一个整数向量Z,下列表达合法的是哪个
Z= 3
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

Z= np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z)#False

27
4
False
3j
3.0
False
[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


In [125]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


G:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
G:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [127]:
#如何从零位对浮点数组做舍入
# Z = np.random.uniform(-10,+10,10)
#(提示: np.uniform, np.copysign, np.ceil, np.abs)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[0. 1. 2. 3. 4.]


In [128]:
#如何找到两个数组中的共同元素? 
#(提示: np.intersect1d)
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


[0 1 2 5 7]


In [ ]:
#如何忽略所有的 numpy 警告(尽管不建议这么做)?
#(提示: np.seterr, np.errstate)
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0


In [131]:
#下面的表达式是正确的吗?
#(提示: imaginary number)
np.sqrt(-1) == np.emath.sqrt(-1)

G:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


False

In [132]:
#如何得到昨天，今天，明天的日期?
#(提示: np.datetime64, np.timedelta64)
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-22
Today is 2019-06-23
Tomorrow is 2019-06-24


In [133]:
#如何得到所有与2016年7月对应的日期？
#(提示: np.arange(dtype=datetime64['D']))
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [134]:
#如何直接在位计算(A+B)\*(-A/2)(不建立副本)? 
#(提示: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [136]:
#用五种不同的方法去提取一个随机数组的整数部分
#(提示: %, np.floor, np.ceil, astype, np.trunc)
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.floor(Z))
print (np.floor(Z))
print (np.floor(Z))

[1. 0. 5. 5. 5. 0. 8. 2. 5. 3.]
[1. 0. 5. 5. 5. 0. 8. 2. 5. 3.]
[1. 0. 5. 5. 5. 0. 8. 2. 5. 3.]
[1. 0. 5. 5. 5. 0. 8. 2. 5. 3.]
[1. 0. 5. 5. 5. 0. 8. 2. 5. 3.]


In [126]:
#对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.17892067  0.214375  ]
